apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: guestbook-pool
  namespace: default
spec:
  addresses:
  - X.X.X.X/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: guestbook-advertisement
  namespace: default
spec:
  ipAddressPools:
  - guestbook-pool